# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fec26d52b1fab45ffeea9fb62eca1bda8b9a3aa1a24c8baf7e5693dba1da9376bcae68442beea22156d5d8cb81f29936ced9e28545bceadf3208d7fedd4a489

test:
  secret_key_base: e9229f0a65d5510572a085a5a37b51f8b3e438db1552a2e9560d06cf58f16c655517592ea90e5f3b86abab9037b8fc32dac7d1220d526533c292694fc2d7a345

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
